apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arsenal-dev-stakater-nordmart-reivew-web
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: arsenal
    stakater.com/env: dev
    stakater.com/kind: dev    
spec:
  destination:
    namespace: arsenal-dev
    server: 'https://kubernetes.default.svc'
  project: arsenal
  source:
    path: arsenal/stakater-nordmart-review-web/dev
    repoURL: 'https://github.com/notstakater/webinar-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true