apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-1-stakater-nordmart-review-api-31111f6b
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: arsenal
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: branch_52817
      timeout: 20s
      url: https://github.com/notstakater/stakater-nordmart-review-api.git
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-branch_52817
          version: '*'
      interval: 1m0s
      releaseName: branch_52817
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/stakater-nordmart-review-api
              tag: snapshot-pr-1-31111f6b
